site_name: PNAPI
site_url: http://pnapi.github.io/
site_description: Plataforma Nacional de Asociaciones de Profesores de Informática
site_author: José Carlos García
repo_url: https://github.com/pnapi/pnapi.github.io/
remote_branch: master
theme: cerulean
pages:
  - "Plataforma Nacional de Asociaciones de Profesores de Informática": "index.md"
